
package com.epam.unit.service;

import com.epam.unit.modelweb.Response;
import com.epam.unit.servicewsimpl.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "UserService", targetNamespace = "http://service.web.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface UserService {


    /**
     * @param lastName
     * @param email
     * @param firstName
     * @param password
     * @return returns com.epam.web.service.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    Response register(
            @WebParam(name = "email", partName = "email")
            String email,
            @WebParam(name = "password", partName = "password")
            String password,
            @WebParam(name = "firstName", partName = "firstName")
            String firstName,
            @WebParam(name = "lastName", partName = "lastName")
            String lastName);

    /**
     * @param id
     * @return returns com.epam.web.service.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    Response delete(
            @WebParam(name = "id", partName = "id")
            String id);

    /**
     * @param role
     * @return returns com.epam.web.service.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    Response getByRoleName(
            @WebParam(name = "role", partName = "role")
            String role);

    /**
     * @param email
     * @param password
     * @return returns com.epam.web.service.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    Response authorize(
            @WebParam(name = "email", partName = "email")
            String email,
            @WebParam(name = "password", partName = "password")
            String password);

    /**
     * @return returns com.epam.web.service.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    Response getAll();

    /**
     * @param email
     * @param password
     * @return returns com.epam.web.service.Response
     */
    @WebMethod
    @WebResult(partName = "return")
    Response login(
            @WebParam(name = "email", partName = "email")
            String email,
            @WebParam(name = "password", partName = "password")
            String password);

}
